export declare function setClass(el: any, cls: string): void;
export declare function addClass(el: any, cls: any): void;
export declare function isInput(el: Element): boolean;
export declare function findupClass(el: Element, cls: string, limit: number): Element | null;
export declare function hasClass(el: Element, cls: string): boolean;
export declare function removeClass(el: Element, cls: string): boolean;
export declare function toggleClass(el: Element, cls: string): void;
export declare function getLastChildElement(el: any): any;
export declare function getFirstChildElement(el: any): any;
export declare function resolveRelativeElement(el: any, str: string): any;
export declare function chainResolveRelativeElement(el: Element, array: string[], i: number): any;
export declare function resolveElement(el: Element, value: any, vm?: any): any;
export declare function resolveElementArray(el: Element, value: any, selectFromParent: boolean, vm: any): any;
export declare function fireEvent(el: any, type: string): void;
export declare function getAbsoluteLeft(el: any): number;
export declare function getAbsoluteTop(el: any): number;
export declare function positionTo(relativeTarget: any, popup: any): void;
export declare function popTo(relativeTarget: any, popup: any): void;
export declare function debounce(func: any, wait: any, immediate: any): () => any;
