export declare function prettydate(value: any): string;
export declare function num(value: any, format?: string): number | string;
export declare function r2(value: any, format?: string): number | string;
export declare function s2h(value: any): string;
export declare function s2m(value: any): string;
export declare function hms(value: any): string;
export declare function hm(value: any): string;
export declare function hm12(value: any, diff: any): string;
export declare function hm12c(value: any, diff: any): string;
export declare function day(value: any): string;
export declare function ymd_day(value: any, separator: any): string;
export declare function md_day(value: any, separator: any): string;
export declare function md_day_html(value: any, separator: any): string;
export declare function d(value: any): string;
export declare function md(value: any, separator: any): string;
export declare function ym(value: any, separator: any): string;
export declare function ymd(value: any, separator: any): string;
export declare function ymdtime(value: any, separator: any): string;
export declare function ymdtimestamp(value: any, separator: any): string;
export declare function ymd2(value: any): string;
export declare function ymdtime2(value: any): string;
export declare function ymdtimestamp2(value: any): string;
