import { Trie } from './trie';
import { Pager, PojoStore } from 'vueds/lib/store/';
export declare function setClass(el: any, cls: string): void;
export declare function addClass(el: any, cls: any): void;
export declare function getUTCOffset(): number;
export declare const UTC_OFFSET: number, HOST_RAW_OFFSET: number, HOST_RAW_OFFSET_SECONDS: number;
export declare function localToUtc(ts: number): number;
export declare function localToUtcSeconds(s: number): number;
export declare function utcToLocal(ts: number): number;
export declare function utcToLocalSeconds(s: number): number;
export declare function newTimeFormatArray(one: any, ago: any, fromNow: any, aSecondAgo: any, justNow: any, seconds: any, minute: any, minutes: any, hour: any, hours: any, yesterday: any, tomorrow: any, days: any, lastWeek: any, nextWeek: any, weeks: any, lastMonth: any, nextMonth: any, months: any, lastYear: any, nextYear: any, years: any, lastCentury: any, nextCentury: any, centuries: any): any[];
export declare const defaultTimeFormatArray: any[];
export declare const regexInt: RegExp, regexDouble: RegExp, regexTime: RegExp, regexDate: RegExp, regexDateTime: RegExp;
export declare const screen: {
    lap: string;
    desk: string;
    wall: string;
    flags: number;
};
export declare function date_columns(): number;
export declare function date_compact_columns(): number;
export declare function table_compact_columns(): number;
export declare function isInput(el: Element): boolean;
export declare function findupClass(el: Element, cls: string, limit: number): Element | null;
export declare function hasClass(el: Element, cls: string): boolean;
export declare function removeClass(el: Element, cls: string): boolean;
export declare function toggleClass(el: Element, cls: string): void;
export declare function getLastChildElement(el: any): any;
export declare function getFirstChildElement(el: any): any;
export declare function resolveRelativeElement(el: any, str: string): any;
export declare function chainResolveRelativeElement(el: Element, array: string[], i: number): any;
export declare function resolveElement(el: Element, value: any, vm?: any): any;
export declare function resolveElementArray(el: Element, value: any, selectFromParent: boolean, vm: any): any;
export declare function resolveNextPageIdx(page: number, idx: number, array: any, pager: Pager): number;
export declare function resolveNextPageIndex(pager: any, idx: number): number;
export declare function selectIdx(idx: number, array: any[], store: PojoStore<any>, clickUpdate: boolean): void;
export declare function pageAndSelectIdx(page: number, idx: number, array: any[], store: PojoStore<any>, clickUpdate: boolean): void;
export declare function tableUp(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableJumpUp(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableDown(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableJumpDown(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableLeft(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableJumpLeft(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableRight(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function tableJumpRight(pager: Pager, col_size: number, flags: number, idx: number, e: Event, clickUpdate: boolean): void;
export declare function extractFlagsLen(str: string): number;
export declare function newChangeHandler(self: any): (e) => any;
export declare function prevent(e: Event, flags: number): boolean;
export declare function isFlagSet(param: any, flag: number): boolean;
/**
 * Returns the param
 */
export declare function putArgsTo(param: any, array: string[], i: number, flags: number): any;
export declare function getFirstVm(el: any): any;
export declare function getValue(obj: any, key: string): any;
export declare function vmGetValue(obj: any, key: string): any;
export declare function vmLookup(target: any, p?: any): any;
export declare function vfragLookup(target: any, p?: any): any;
export declare function vmGetHandler(vm: any): any;
export declare function setValue(obj: any, key: string, value: any): void;
export declare function getObjAndKey(obj: any, key: string): any;
export declare function getObj(obj: any, key: string): any;
export declare function fireEvent(el: any, type: string): void;
export declare function prettyDate(ts: number, targetTimeFormatArray: string[], ago?: string, fromNow?: string): string;
export declare function formatDate2(date: Date, fmt: string): string;
export declare function toDay(date: Date): string;
export declare function toD(date: Date): string;
export declare function toMD(date: Date, separator: string): string;
export declare function toYM(date: Date, separator: string): string;
export declare function toYMD(date: Date, separator: string): string;
export declare function toYMDTime(dt: Date, separator: string): string;
export declare function removeTime(date: Date): Date;
export declare function formatTime(v: any): string;
export declare function formatDate(v: any): string;
export declare function formatDateTime(v: any): string;
export declare function isValidDateStr(text: string): number | null;
export declare function isValidDateTimeStr(dt: any): number | null;
export declare function getAbsoluteLeft(el: any): number;
export declare function getAbsoluteTop(el: any): number;
export declare function positionTo(relativeTarget: any, popup: any): void;
export declare function popTo(relativeTarget: any, popup: any): void;
export declare function debounce(func: any, wait: any, immediate: any): () => any;
export declare function newTrie(stem: any, sorting: any): Trie;
